[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
new_qup_staking = "69GqjmqyXcL593ByVF4YqrFzBxHX5DsVcSRsAk49pPq7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet-user.json"

[workspace]
members = ["programs/new_qup_staking"]
