cd ~/krakenbot/pro/questakingpool/new_qup_staking

# Create a targeted fix in your root Cargo.toml
cat > Cargo.toml << 'EOF'
[workspace]
members = ["programs/new_qup_staking"]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

# Targeted patch ONLY for the conflicting dependency
# This preserves your anchor-lang and anchor-spl versions exactly
[patch.crates-io]
solana-address-lookup-table-interface = { version = "2.2.2" }
EOF

# Clean up and regenerate Cargo.lock (keeping it as version 3)
rm -f Cargo.lock

# Generate new lockfile
cargo generate-lockfile

# Force Cargo.lock to version 3 (your requirement)
# Check current version
CURRENT_VERSION=$(head -n 10 Cargo.lock | grep "^version = " | head -n 1 | sed 's/version = //' | tr -d '"' | tr -d ' ')
echo "Current Cargo.lock version: $CURRENT_VERSION"

if [ "$CURRENT_VERSION" != "3" ]; then
    echo "Converting to version 3..."
    # Save content after version line
    tail -n +4 Cargo.lock > Cargo.lock.tmp
    
    # Create new header with version 3
    cat > Cargo.lock << 'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3
EOF
    
    # Append saved content
    cat Cargo.lock.tmp >> Cargo.lock
    rm Cargo.lock.tmp
    
    echo "✅ Cargo.lock is now version 3"
fi

# Now try building
echo "Attempting build with targeted fix..."
anchor build
